import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("root layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/menu1">menu 1</Link>
            </li>
            <li>
              <Link href="/menu2">menu 2</Link>
            </li>
            <li>
              <Link href="/menu3">menu 3</Link>
            </li>
          </ul>
        </nav>
        <section>{children}</section>
      </body>
    </html>
  );
}
