import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("root layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <nav>
            <ul>
              <li>
                <Link href="/">home</Link>
              </li>
              <li>
                <Link href="/post">post</Link>
              </li>
            </ul>
          </nav>
        </section>
        <section>{children}</section>
      </body>
    </html>
  );
}
